apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubevela
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vela-core
    repoURL: https://kubevela.github.io/charts/
    targetRevision: "1.9.*"
    helm:
      values: |
        image:
          repository: tanjim/vela-core
          tag: latest
          pullPolicy: Always
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
