apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
spec:
  destination:
    namespace: kubevela
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vela-core
    repoURL: https://kubevela.github.io/charts/
    targetRevision: v1.9.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
