apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: compaas
build:
  artifacts:
    - image: compaas
      context: target/docker/stage
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev
