kind: Deployment
apiVersion: apps/v1
metadata:
  name: compaas
spec:
  replicas: 1
  strategy:
    type: Recreate
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
