apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service.yaml

configMapGenerator:
  - name: compaas-cm
    behavior: merge
    env: config.properties

patchesStrategicMerge:
  - deployments.yaml
