apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- service.yaml

configMapGenerator:
- behavior: merge
  envs:
  - config.properties
  name: compaas-cm

patches:
- path: deployments.yaml
