kind: Deployment
apiVersion: apps/v1
metadata:
  name: compaas
spec:
  template:
    spec:
      containers:
        - name: compaas
          image: compaas:latest
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jmx
              containerPort: 9010
              protocol: TCP
            - name: debugger
              containerPort: 9020
              protocol: TCP
          envFrom:
            - configMapRef:
                name: compaas-cm
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
