apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: compaas

configMapGenerator:
  - name: compaas-cm
    env: config.properties

resources:
  - deployments.yaml
  - rbac.yaml
