version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ubuntu-22.04
    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
