services:
  devcontainer:
    build:
      context: .
      args:
        - GRAAL_EE_DOWNLOAD_TOKEN
        - GRAALVM_HOME
    environment:
      - PULUMI_ACCESS_TOKEN
      - PULUMI_BACKEND_URL
      - PULUMI_CONFIG_PASSPHRASE
      - PULUMI_DEFAULT_ORG
    volumes:
      - ../..:/workspaces:rw,cached
    init: true

    command: sleep infinity
