services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    environment:
      - GRAAL_EE_DOWNLOAD_TOKEN
      - PULUMI_ACCESS_TOKEN
      - PULUMI_BACKEND_URL
      - PULUMI_CONFIG_PASSPHRASE
      - PULUMI_DEFAULT_ORG
    volumes:
      - ../..:/workspaces:cached
    init: true

    command: sleep infinity
