services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    environment:
      - GRAAL_EE_DOWNLOAD_TOKEN
    volumes:
      - ../..:/workspaces:cached
    init: true

    command: sleep infinity
