version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRAALVM_EDITION: ${GRAALVM_EDITION:-ce}
        GRAAL_EE_DOWNLOAD_TOKEN: ${GRAAL_EE_DOWNLOAD_TOKEN}
    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
