#!/usr/bin/env bash

concurrently \
    --restart-tries -1 \
    --restart-after 1000 \
    --success 'all' \
    --names 'build,deploy' \
    --prefix-colors 'cyan,magenta' \
        'sbt --client -J-Xmx2G "~Docker / stage"' \
        'tilt up'