kind: Deployment
apiVersion: apps/v1
metadata:
  name: compaas
spec:
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
