apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
  - https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
  - namespace.yaml
  - ../../base
  - otel-collector.yaml
  - otel-instrumentation.yaml

configMapGenerator:
  - name: compaas-cm
    behavior: merge
    env: config.properties

patchesStrategicMerge:
  - deployments.yaml
